export const CONFIG = {
  WS_URL: '/ws/leaderboard',
  SUBMISSION_POLL_INTERVAL: 1500,
  SUBMISSION_POLL_TIMEOUT: 60_000,
  LEADERBOARD_POLL_FALLBACK: 10_000,
  PAGE_SIZE_DEFAULT: 20,
  PAGE_SIZE_LEADERBOARD: 50,
  CODE_SIZE_LIMIT: 64_000,
} as const;
